### PR TITLE
Declare support of Drupal 10

### PR DESCRIPTION
**Pull request by iVegas**

### CODE REVIEW

**Comment by jeremypeter** [comment]
Here's a patch that can be used for now:
[yaml_editor-8.x-1.x-drupal-10-compatibility-fixes.patch](https://github.com/yannickoo/yaml_editor/files/10828865/yaml_editor-8.x-1.x-drupal-10-compatibility-fixes.patch)

- Updates version requirement to be Drupal ^9.3 || ^10
- Refactors JS to remove jQuery in favor of vanilla JS
- Removes jQuery and jQuery Once library dependencies
- Uses Drupal core's `once` library

**Comment by cateprNIH** [comment]
@jeremypeter can you create a PR with your patch changes?

**Comment by iVegas** [comment]
Thanks for the patch, applied to the PR

**Comment by wayne-weibel** [comment]
Any chance someone can pick this module up and merge/release the D10 version?

**Comment by b-khouy** [comment]
@jeremypeter's patch could not be applied 
image

I've updated the patch to be applied correctly: 
[https://gist.githubusercontent.com/b-khouy/b249e0a35a2ece62fe741ad330490b8e/raw/efb9a48d26957608b4353bbb2c48e09dd566437a/yaml-editor-D10-compatibility.patch](https://gist.githubusercontent.com/b-khouy/b249e0a35a2ece62fe741ad330490b8e/raw/efb9a48d26957608b4353bbb2c48e09dd566437a/yaml-editor-D10-compatibility.patch)

**Comment by iVegas** [comment]
This PR already include the patch. Check the diff https://patch-diff.githubusercontent.com/raw/yannickoo/yaml_editor/pull/20.diff

**Comment by asgharkhan** [comment]
Hi @iVegas , 
When Drupal 10 compatible release will be available?. Thanks

**Comment by b-khouy** [comment]
@asgharkhan You could temporarily use this package **b-khouy/yaml_editor**
`composer require b-khouy/yaml_editor`

**Comment by yannickoo** [comment]
This has been fixed in the latest commit 😇

**Pull request closed without merging**
